// Flexbox and Grid rules for Tailwind CSS classes
export const flexboxRules = {
	// Flex Direction
	'flex-row': 'flex-direction: row;',
	'flex-row-reverse': 'flex-direction: row-reverse;',
	'flex-col': 'flex-direction: column;',
	'flex-col-reverse': 'flex-direction: column-reverse;',

	// Flex Wrap
	'flex-wrap': 'flex-wrap: wrap;',
	'flex-nowrap': 'flex-wrap: nowrap;',
	'flex-wrap-reverse': 'flex-wrap: wrap-reverse;',

	// Flex
	'flex-1': 'flex: 1 1 0%;',
	'flex-auto': 'flex: 1 1 auto;',
	'flex-initial': 'flex: 0 1 auto;',
	'flex-none': 'flex: none;',

	// Flex Grow
	'grow-0': 'flex-grow: 0;',
	grow: 'flex-grow: 1;',

	// Flex Shrink
	'shrink-0': 'flex-shrink: 0;',
	shrink: 'flex-shrink: 1;',

	// Flex Basis
	'basis-0': 'flex-basis: 0px;',
	'basis-0.5': 'flex-basis: calc(var(--spacing) * 0.125);',
	'basis-1': 'flex-basis: calc(var(--spacing) * 0.25);',
	'basis-1.5': 'flex-basis: calc(var(--spacing) * 0.375);',
	'basis-2': 'flex-basis: calc(var(--spacing) * 0.5);',
	'basis-2.5': 'flex-basis: calc(var(--spacing) * 0.625);',
	'basis-3': 'flex-basis: calc(var(--spacing) * 0.75);',
	'basis-3.5': 'flex-basis: calc(var(--spacing) * 0.875);',
	'basis-4': 'flex-basis: calc(var(--spacing) * 1);',
	'basis-5': 'flex-basis: calc(var(--spacing) * 1.25);',
	'basis-6': 'flex-basis: calc(var(--spacing) * 1.5);',
	'basis-7': 'flex-basis: calc(var(--spacing) * 1.75);',
	'basis-8': 'flex-basis: calc(var(--spacing) * 2);',
	'basis-9': 'flex-basis: calc(var(--spacing) * 2.25);',
	'basis-10': 'flex-basis: calc(var(--spacing) * 2.5);',
	'basis-11': 'flex-basis: calc(var(--spacing) * 2.75);',
	'basis-12': 'flex-basis: calc(var(--spacing) * 3);',
	'basis-14': 'flex-basis: calc(var(--spacing) * 3.5);',
	'basis-16': 'flex-basis: calc(var(--spacing) * 4);',
	'basis-20': 'flex-basis: calc(var(--spacing) * 5);',
	'basis-24': 'flex-basis: calc(var(--spacing) * 6);',
	'basis-28': 'flex-basis: calc(var(--spacing) * 7);',
	'basis-32': 'flex-basis: calc(var(--spacing) * 8);',
	'basis-36': 'flex-basis: calc(var(--spacing) * 9);',
	'basis-40': 'flex-basis: calc(var(--spacing) * 10);',
	'basis-44': 'flex-basis: calc(var(--spacing) * 11);',
	'basis-48': 'flex-basis: calc(var(--spacing) * 12);',
	'basis-52': 'flex-basis: calc(var(--spacing) * 13);',
	'basis-56': 'flex-basis: calc(var(--spacing) * 14);',
	'basis-60': 'flex-basis: calc(var(--spacing) * 15);',
	'basis-64': 'flex-basis: calc(var(--spacing) * 16);',
	'basis-72': 'flex-basis: calc(var(--spacing) * 18);',
	'basis-80': 'flex-basis: calc(var(--spacing) * 20);',
	'basis-96': 'flex-basis: calc(var(--spacing) * 24);',
	'basis-auto': 'flex-basis: auto;',
	'basis-1/2': 'flex-basis: calc(1/2 * 100%);',
	'basis-1/3': 'flex-basis: calc(1/3 * 100%);',
	'basis-2/3': 'flex-basis: calc(2/3 * 100%);',
	'basis-1/4': 'flex-basis: calc(1/4 * 100%);',
	'basis-2/4': 'flex-basis: calc(2/4 * 100%);',
	'basis-3/4': 'flex-basis: calc(3/4 * 100%);',
	'basis-1/5': 'flex-basis: calc(1/5 * 100%);',
	'basis-2/5': 'flex-basis: calc(2/5 * 100%);',
	'basis-3/5': 'flex-basis: calc(3/5 * 100%);',
	'basis-4/5': 'flex-basis: calc(4/5 * 100%);',
	'basis-1/6': 'flex-basis: calc(1/6 * 100%);',
	'basis-2/6': 'flex-basis: calc(2/6 * 100%);',
	'basis-3/6': 'flex-basis: calc(3/6 * 100%);',
	'basis-4/6': 'flex-basis: calc(4/6 * 100%);',
	'basis-5/6': 'flex-basis: calc(5/6 * 100%);',
	'basis-1/12': 'flex-basis: calc(1/12 * 100%);',
	'basis-2/12': 'flex-basis: calc(2/12 * 100%);',
	'basis-3/12': 'flex-basis: calc(3/12 * 100%);',
	'basis-4/12': 'flex-basis: calc(4/12 * 100%);',
	'basis-5/12': 'flex-basis: calc(5/12 * 100%);',
	'basis-6/12': 'flex-basis: calc(6/12 * 100%);',
	'basis-7/12': 'flex-basis: calc(7/12 * 100%);',
	'basis-8/12': 'flex-basis: calc(8/12 * 100%);',
	'basis-9/12': 'flex-basis: calc(9/12 * 100%);',
	'basis-10/12': 'flex-basis: calc(10/12 * 100%);',
	'basis-11/12': 'flex-basis: calc(11/12 * 100%);',
	'basis-full': 'flex-basis: 100%;',

	// Order
	'order-1': 'order: 1;',
	'order-2': 'order: 2;',
	'order-3': 'order: 3;',
	'order-4': 'order: 4;',
	'order-5': 'order: 5;',
	'order-6': 'order: 6;',
	'order-7': 'order: 7;',
	'order-8': 'order: 8;',
	'order-9': 'order: 9;',
	'order-10': 'order: 10;',
	'order-11': 'order: 11;',
	'order-12': 'order: 12;',
	'order-first': 'order: -9999;',
	'order-last': 'order: 9999;',
	'order-none': 'order: 0;',

	// Grid Template Columns
	'grid-cols-1': 'grid-template-columns: repeat(1, minmax(0, 1fr));',
	'grid-cols-2': 'grid-template-columns: repeat(2, minmax(0, 1fr));',
	'grid-cols-3': 'grid-template-columns: repeat(3, minmax(0, 1fr));',
	'grid-cols-4': 'grid-template-columns: repeat(4, minmax(0, 1fr));',
	'grid-cols-5': 'grid-template-columns: repeat(5, minmax(0, 1fr));',
	'grid-cols-6': 'grid-template-columns: repeat(6, minmax(0, 1fr));',
	'grid-cols-7': 'grid-template-columns: repeat(7, minmax(0, 1fr));',
	'grid-cols-8': 'grid-template-columns: repeat(8, minmax(0, 1fr));',
	'grid-cols-9': 'grid-template-columns: repeat(9, minmax(0, 1fr));',
	'grid-cols-10': 'grid-template-columns: repeat(10, minmax(0, 1fr));',
	'grid-cols-11': 'grid-template-columns: repeat(11, minmax(0, 1fr));',
	'grid-cols-12': 'grid-template-columns: repeat(12, minmax(0, 1fr));',
	'grid-cols-none': 'grid-template-columns: none;',

	// Grid Template Rows
	'grid-rows-1': 'grid-template-rows: repeat(1, minmax(0, 1fr));',
	'grid-rows-2': 'grid-template-rows: repeat(2, minmax(0, 1fr));',
	'grid-rows-3': 'grid-template-rows: repeat(3, minmax(0, 1fr));',
	'grid-rows-4': 'grid-template-rows: repeat(4, minmax(0, 1fr));',
	'grid-rows-5': 'grid-template-rows: repeat(5, minmax(0, 1fr));',
	'grid-rows-6': 'grid-template-rows: repeat(6, minmax(0, 1fr));',
	'grid-rows-none': 'grid-template-rows: none;',

	// Grid Column Start/End
	'col-auto': 'grid-column: auto;',
	'col-span-1': 'grid-column: span 1 / span 1;',
	'col-span-2': 'grid-column: span 2 / span 2;',
	'col-span-3': 'grid-column: span 3 / span 3;',
	'col-span-4': 'grid-column: span 4 / span 4;',
	'col-span-5': 'grid-column: span 5 / span 5;',
	'col-span-6': 'grid-column: span 6 / span 6;',
	'col-span-7': 'grid-column: span 7 / span 7;',
	'col-span-8': 'grid-column: span 8 / span 8;',
	'col-span-9': 'grid-column: span 9 / span 9;',
	'col-span-10': 'grid-column: span 10 / span 10;',
	'col-span-11': 'grid-column: span 11 / span 11;',
	'col-span-12': 'grid-column: span 12 / span 12;',
	'col-span-full': 'grid-column: 1 / -1;',

	'col-start-1': 'grid-column-start: 1;',
	'col-start-2': 'grid-column-start: 2;',
	'col-start-3': 'grid-column-start: 3;',
	'col-start-4': 'grid-column-start: 4;',
	'col-start-5': 'grid-column-start: 5;',
	'col-start-6': 'grid-column-start: 6;',
	'col-start-7': 'grid-column-start: 7;',
	'col-start-8': 'grid-column-start: 8;',
	'col-start-9': 'grid-column-start: 9;',
	'col-start-10': 'grid-column-start: 10;',
	'col-start-11': 'grid-column-start: 11;',
	'col-start-12': 'grid-column-start: 12;',
	'col-start-13': 'grid-column-start: 13;',
	'col-start-auto': 'grid-column-start: auto;',

	'col-end-1': 'grid-column-end: 1;',
	'col-end-2': 'grid-column-end: 2;',
	'col-end-3': 'grid-column-end: 3;',
	'col-end-4': 'grid-column-end: 4;',
	'col-end-5': 'grid-column-end: 5;',
	'col-end-6': 'grid-column-end: 6;',
	'col-end-7': 'grid-column-end: 7;',
	'col-end-8': 'grid-column-end: 8;',
	'col-end-9': 'grid-column-end: 9;',
	'col-end-10': 'grid-column-end: 10;',
	'col-end-11': 'grid-column-end: 11;',
	'col-end-12': 'grid-column-end: 12;',
	'col-end-13': 'grid-column-end: 13;',
	'col-end-auto': 'grid-column-end: auto;',

	// Grid Row Start/End
	'row-auto': 'grid-row: auto;',
	'row-span-1': 'grid-row: span 1 / span 1;',
	'row-span-2': 'grid-row: span 2 / span 2;',
	'row-span-3': 'grid-row: span 3 / span 3;',
	'row-span-4': 'grid-row: span 4 / span 4;',
	'row-span-5': 'grid-row: span 5 / span 5;',
	'row-span-6': 'grid-row: span 6 / span 6;',
	'row-span-full': 'grid-row: 1 / -1;',

	'row-start-1': 'grid-row-start: 1;',
	'row-start-2': 'grid-row-start: 2;',
	'row-start-3': 'grid-row-start: 3;',
	'row-start-4': 'grid-row-start: 4;',
	'row-start-5': 'grid-row-start: 5;',
	'row-start-6': 'grid-row-start: 6;',
	'row-start-7': 'grid-row-start: 7;',
	'row-start-auto': 'grid-row-start: auto;',

	'row-end-1': 'grid-row-end: 1;',
	'row-end-2': 'grid-row-end: 2;',
	'row-end-3': 'grid-row-end: 3;',
	'row-end-4': 'grid-row-end: 4;',
	'row-end-5': 'grid-row-end: 5;',
	'row-end-6': 'grid-row-end: 6;',
	'row-end-7': 'grid-row-end: 7;',
	'row-end-auto': 'grid-row-end: auto;',

	// Gap
	'gap-0': 'gap: 0;',
	'gap-0.5': 'gap: calc(var(--spacing) * 0.125);',
	'gap-1': 'gap: calc(var(--spacing) * 0.25);',
	'gap-1.5': 'gap: calc(var(--spacing) * 0.375);',
	'gap-2': 'gap: calc(var(--spacing) * 0.5);',
	'gap-2.5': 'gap: calc(var(--spacing) * 0.625);',
	'gap-3': 'gap: calc(var(--spacing) * 0.75);',
	'gap-3.5': 'gap: calc(var(--spacing) * 0.875);',
	'gap-4': 'gap: calc(var(--spacing) * 1);',
	'gap-5': 'gap: calc(var(--spacing) * 1.25);',
	'gap-6': 'gap: calc(var(--spacing) * 1.5);',
	'gap-7': 'gap: calc(var(--spacing) * 1.75);',
	'gap-8': 'gap: calc(var(--spacing) * 2);',
	'gap-9': 'gap: calc(var(--spacing) * 2.25);',
	'gap-10': 'gap: calc(var(--spacing) * 2.5);',
	'gap-11': 'gap: calc(var(--spacing) * 2.75);',
	'gap-12': 'gap: calc(var(--spacing) * 3);',
	'gap-14': 'gap: calc(var(--spacing) * 3.5);',
	'gap-16': 'gap: calc(var(--spacing) * 4);',
	'gap-20': 'gap: calc(var(--spacing) * 5);',
	'gap-24': 'gap: calc(var(--spacing) * 6);',
	'gap-28': 'gap: calc(var(--spacing) * 7);',
	'gap-32': 'gap: calc(var(--spacing) * 8);',
	'gap-36': 'gap: calc(var(--spacing) * 9);',
	'gap-40': 'gap: calc(var(--spacing) * 10);',
	'gap-44': 'gap: calc(var(--spacing) * 11);',
	'gap-48': 'gap: calc(var(--spacing) * 12);',
	'gap-52': 'gap: calc(var(--spacing) * 13);',
	'gap-56': 'gap: calc(var(--spacing) * 14);',
	'gap-60': 'gap: calc(var(--spacing) * 15);',
	'gap-64': 'gap: calc(var(--spacing) * 16);',
	'gap-72': 'gap: calc(var(--spacing) * 18);',
	'gap-80': 'gap: calc(var(--spacing) * 20);',
	'gap-96': 'gap: calc(var(--spacing) * 24);',
	'gap-px': 'gap: 1px;',

	// Row Gap
	'row-gap-0': 'row-gap: 0;',
	'row-gap-0.5': 'row-gap: calc(var(--spacing) * 0.125);',
	'row-gap-1': 'row-gap: calc(var(--spacing) * 0.25);',
	'row-gap-1.5': 'row-gap: calc(var(--spacing) * 0.375);',
	'row-gap-2': 'row-gap: calc(var(--spacing) * 0.5);',
	'row-gap-2.5': 'row-gap: calc(var(--spacing) * 0.625);',
	'row-gap-3': 'row-gap: calc(var(--spacing) * 0.75);',
	'row-gap-3.5': 'row-gap: calc(var(--spacing) * 0.875);',
	'row-gap-4': 'row-gap: calc(var(--spacing) * 1);',
	'row-gap-5': 'row-gap: calc(var(--spacing) * 1.25);',
	'row-gap-6': 'row-gap: calc(var(--spacing) * 1.5);',
	'row-gap-7': 'row-gap: calc(var(--spacing) * 1.75);',
	'row-gap-8': 'row-gap: calc(var(--spacing) * 2);',
	'row-gap-9': 'row-gap: calc(var(--spacing) * 2.25);',
	'row-gap-10': 'row-gap: calc(var(--spacing) * 2.5);',
	'row-gap-11': 'row-gap: calc(var(--spacing) * 2.75);',
	'row-gap-12': 'row-gap: calc(var(--spacing) * 3);',
	'row-gap-14': 'row-gap: calc(var(--spacing) * 3.5);',
	'row-gap-16': 'row-gap: calc(var(--spacing) * 4);',
	'row-gap-20': 'row-gap: calc(var(--spacing) * 5);',
	'row-gap-24': 'row-gap: calc(var(--spacing) * 6);',
	'row-gap-28': 'row-gap: calc(var(--spacing) * 7);',
	'row-gap-32': 'row-gap: calc(var(--spacing) * 8);',
	'row-gap-36': 'row-gap: calc(var(--spacing) * 9);',
	'row-gap-40': 'row-gap: calc(var(--spacing) * 10);',
	'row-gap-44': 'row-gap: calc(var(--spacing) * 11);',
	'row-gap-48': 'row-gap: calc(var(--spacing) * 12);',
	'row-gap-52': 'row-gap: calc(var(--spacing) * 13);',
	'row-gap-56': 'row-gap: calc(var(--spacing) * 14);',
	'row-gap-60': 'row-gap: calc(var(--spacing) * 15);',
	'row-gap-64': 'row-gap: calc(var(--spacing) * 16);',
	'row-gap-72': 'row-gap: calc(var(--spacing) * 18);',
	'row-gap-80': 'row-gap: calc(var(--spacing) * 20);',
	'row-gap-96': 'row-gap: calc(var(--spacing) * 24);',
	'row-gap-px': 'row-gap: 1px;',

	// Column Gap
	'col-gap-0': 'column-gap: 0;',
	'col-gap-0.5': 'column-gap: calc(var(--spacing) * 0.125);',
	'col-gap-1': 'column-gap: calc(var(--spacing) * 0.25);',
	'col-gap-1.5': 'column-gap: calc(var(--spacing) * 0.375);',
	'col-gap-2': 'column-gap: calc(var(--spacing) * 0.5);',
	'col-gap-2.5': 'column-gap: calc(var(--spacing) * 0.625);',
	'col-gap-3': 'column-gap: calc(var(--spacing) * 0.75);',
	'col-gap-3.5': 'column-gap: calc(var(--spacing) * 0.875);',
	'col-gap-4': 'column-gap: calc(var(--spacing) * 1);',
	'col-gap-5': 'column-gap: calc(var(--spacing) * 1.25);',
	'col-gap-6': 'column-gap: calc(var(--spacing) * 1.5);',
	'col-gap-7': 'column-gap: calc(var(--spacing) * 1.75);',
	'col-gap-8': 'column-gap: calc(var(--spacing) * 2);',
	'col-gap-9': 'column-gap: calc(var(--spacing) * 2.25);',
	'col-gap-10': 'column-gap: calc(var(--spacing) * 2.5);',
	'col-gap-11': 'column-gap: calc(var(--spacing) * 2.75);',
	'col-gap-12': 'column-gap: calc(var(--spacing) * 3);',
	'col-gap-14': 'column-gap: calc(var(--spacing) * 3.5);',
	'col-gap-16': 'column-gap: calc(var(--spacing) * 4);',
	'col-gap-20': 'column-gap: calc(var(--spacing) * 5);',
	'col-gap-24': 'column-gap: calc(var(--spacing) * 6);',
	'col-gap-28': 'column-gap: calc(var(--spacing) * 7);',
	'col-gap-32': 'column-gap: calc(var(--spacing) * 8);',
	'col-gap-36': 'column-gap: calc(var(--spacing) * 9);',
	'col-gap-40': 'column-gap: calc(var(--spacing) * 10);',
	'col-gap-44': 'column-gap: calc(var(--spacing) * 11);',
	'col-gap-48': 'column-gap: calc(var(--spacing) * 12);',
	'col-gap-52': 'column-gap: calc(var(--spacing) * 13);',
	'col-gap-56': 'column-gap: calc(var(--spacing) * 14);',
	'col-gap-60': 'column-gap: calc(var(--spacing) * 15);',
	'col-gap-64': 'column-gap: calc(var(--spacing) * 16);',
	'col-gap-72': 'column-gap: calc(var(--spacing) * 18);',
	'col-gap-80': 'column-gap: calc(var(--spacing) * 20);',
	'col-gap-96': 'column-gap: calc(var(--spacing) * 24);',
	'col-gap-px': 'column-gap: 1px;',

	// Justify Content
	'justify-start': 'justify-content: flex-start;',
	'justify-end': 'justify-content: flex-end;',
	'justify-center': 'justify-content: center;',
	'justify-between': 'justify-content: space-between;',
	'justify-around': 'justify-content: space-around;',
	'justify-evenly': 'justify-content: space-evenly;',

	// Justify Items
	'justify-items-start': 'justify-items: start;',
	'justify-items-end': 'justify-items: end;',
	'justify-items-center': 'justify-items: center;',
	'justify-items-stretch': 'justify-items: stretch;',

	// Justify Self
	'justify-self-auto': 'justify-self: auto;',
	'justify-self-start': 'justify-self: start;',
	'justify-self-end': 'justify-self: end;',
	'justify-self-center': 'justify-self: center;',
	'justify-self-stretch': 'justify-self: stretch;',

	// Align Content
	'content-start': 'align-content: flex-start;',
	'content-end': 'align-content: flex-end;',
	'content-center': 'align-content: center;',
	'content-between': 'align-content: space-between;',
	'content-around': 'align-content: space-around;',
	'content-evenly': 'align-content: space-evenly;',

	// Align Items
	'items-start': 'align-items: flex-start;',
	'items-end': 'align-items: flex-end;',
	'items-center': 'align-items: center;',
	'items-baseline': 'align-items: baseline;',
	'items-stretch': 'align-items: stretch;',

	// Align Self
	'self-auto': 'align-self: auto;',
	'self-start': 'align-self: flex-start;',
	'self-end': 'align-self: flex-end;',
	'self-center': 'align-self: center;',
	'self-stretch': 'align-self: stretch;',
	'self-baseline': 'align-self: baseline;',

	// Place Content
	'place-content-start': 'place-content: start;',
	'place-content-end': 'place-content: end;',
	'place-content-center': 'place-content: center;',
	'place-content-between': 'place-content: space-between;',
	'place-content-around': 'place-content: space-around;',
	'place-content-evenly': 'place-content: space-evenly;',
	'place-content-baseline': 'place-content: baseline;',
	'place-content-stretch': 'place-content: stretch;',

	// Place Items
	'place-items-start': 'place-items: start;',
	'place-items-end': 'place-items: end;',
	'place-items-center': 'place-items: center;',
	'place-items-baseline': 'place-items: baseline;',
	'place-items-stretch': 'place-items: stretch;',

	// Place Self
	'place-self-auto': 'place-self: auto;',
	'place-self-start': 'place-self: start;',
	'place-self-end': 'place-self: end;',
	'place-self-center': 'place-self: center;',
	'place-self-stretch': 'place-self: stretch;',
}
