// Layout rules for Tailwind CSS classes
export const layoutRules = {
	// Display
	block: 'display: block;',
	'inline-block': 'display: inline-block;',
	inline: 'display: inline;',
	flex: 'display: flex;',
	'inline-flex': 'display: inline-flex;',
	table: 'display: table;',
	'inline-table': 'display: inline-table;',
	'table-caption': 'display: table-caption;',
	'table-cell': 'display: table-cell;',
	'table-column': 'display: table-column;',
	'table-column-group': 'display: table-column-group;',
	'table-footer-group': 'display: table-footer-group;',
	'table-header-group': 'display: table-header-group;',
	'table-row-group': 'display: table-row-group;',
	'table-row': 'display: table-row;',
	'flow-root': 'display: flow-root;',
	grid: 'display: grid;',
	'inline-grid': 'display: inline-grid;',
	contents: 'display: contents;',
	'list-item': 'display: list-item;',
	hidden: 'display: none;',

	// Position
	static: 'position: static;',
	fixed: 'position: fixed;',
	absolute: 'position: absolute;',
	relative: 'position: relative;',
	sticky: 'position: sticky;',

	// Z-index
	'z-0': 'z-index: 0;',
	'z-10': 'z-index: 10;',
	'z-20': 'z-index: 20;',
	'z-30': 'z-index: 30;',
	'z-40': 'z-index: 40;',
	'z-50': 'z-index: 50;',
	'z-auto': 'z-index: auto;',

	// Top
	'top-0': 'top: 0;',
	'top-0.5': 'top: calc(var(--spacing) * 0.125);',
	'top-1': 'top: calc(var(--spacing) * 0.25);',
	'top-1.5': 'top: calc(var(--spacing) * 0.375);',
	'top-2': 'top: calc(var(--spacing) * 0.5);',
	'top-2.5': 'top: calc(var(--spacing) * 0.625);',
	'top-3': 'top: calc(var(--spacing) * 0.75);',
	'top-3.5': 'top: calc(var(--spacing) * 0.875);',
	'top-4': 'top: calc(var(--spacing) * 1);',
	'top-5': 'top: calc(var(--spacing) * 1.25);',
	'top-6': 'top: calc(var(--spacing) * 1.5);',
	'top-7': 'top: calc(var(--spacing) * 1.75);',
	'top-8': 'top: calc(var(--spacing) * 2);',
	'top-9': 'top: calc(var(--spacing) * 2.25);',
	'top-10': 'top: calc(var(--spacing) * 2.5);',
	'top-11': 'top: calc(var(--spacing) * 2.75);',
	'top-12': 'top: calc(var(--spacing) * 3);',
	'top-14': 'top: calc(var(--spacing) * 3.5);',
	'top-16': 'top: calc(var(--spacing) * 4);',
	'top-20': 'top: calc(var(--spacing) * 5);',
	'top-24': 'top: calc(var(--spacing) * 6);',
	'top-28': 'top: calc(var(--spacing) * 7);',
	'top-32': 'top: calc(var(--spacing) * 8);',
	'top-36': 'top: calc(var(--spacing) * 9);',
	'top-40': 'top: calc(var(--spacing) * 10);',
	'top-44': 'top: calc(var(--spacing) * 11);',
	'top-48': 'top: calc(var(--spacing) * 12);',
	'top-52': 'top: calc(var(--spacing) * 13);',
	'top-56': 'top: calc(var(--spacing) * 14);',
	'top-60': 'top: calc(var(--spacing) * 15);',
	'top-64': 'top: calc(var(--spacing) * 16);',
	'top-72': 'top: calc(var(--spacing) * 18);',
	'top-80': 'top: calc(var(--spacing) * 20);',
	'top-96': 'top: calc(var(--spacing) * 24);',
	'top-auto': 'top: auto;',

	// Right
	'right-0': 'right: 0;',
	'right-0.5': 'right: calc(var(--spacing) * 0.125);',
	'right-1': 'right: calc(var(--spacing) * 0.25);',
	'right-1.5': 'right: calc(var(--spacing) * 0.375);',
	'right-2': 'right: calc(var(--spacing) * 0.5);',
	'right-2.5': 'right: calc(var(--spacing) * 0.625);',
	'right-3': 'right: calc(var(--spacing) * 0.75);',
	'right-3.5': 'right: calc(var(--spacing) * 0.875);',
	'right-4': 'right: calc(var(--spacing) * 1);',
	'right-5': 'right: calc(var(--spacing) * 1.25);',
	'right-6': 'right: calc(var(--spacing) * 1.5);',
	'right-7': 'right: calc(var(--spacing) * 1.75);',
	'right-8': 'right: calc(var(--spacing) * 2);',
	'right-9': 'right: calc(var(--spacing) * 2.25);',
	'right-10': 'right: calc(var(--spacing) * 2.5);',
	'right-11': 'right: calc(var(--spacing) * 2.75);',
	'right-12': 'right: calc(var(--spacing) * 3);',
	'right-14': 'right: calc(var(--spacing) * 3.5);',
	'right-16': 'right: calc(var(--spacing) * 4);',
	'right-20': 'right: calc(var(--spacing) * 5);',
	'right-24': 'right: calc(var(--spacing) * 6);',
	'right-28': 'right: calc(var(--spacing) * 7);',
	'right-32': 'right: calc(var(--spacing) * 8);',
	'right-36': 'right: calc(var(--spacing) * 9);',
	'right-40': 'right: calc(var(--spacing) * 10);',
	'right-44': 'right: calc(var(--spacing) * 11);',
	'right-48': 'right: calc(var(--spacing) * 12);',
	'right-52': 'right: calc(var(--spacing) * 13);',
	'right-56': 'right: calc(var(--spacing) * 14);',
	'right-60': 'right: calc(var(--spacing) * 15);',
	'right-64': 'right: calc(var(--spacing) * 16);',
	'right-72': 'right: calc(var(--spacing) * 18);',
	'right-80': 'right: calc(var(--spacing) * 20);',
	'right-96': 'right: calc(var(--spacing) * 24);',
	'right-auto': 'right: auto;',

	// Bottom
	'bottom-0': 'bottom: 0;',
	'bottom-0.5': 'bottom: calc(var(--spacing) * 0.125);',
	'bottom-1': 'bottom: calc(var(--spacing) * 0.25);',
	'bottom-1.5': 'bottom: calc(var(--spacing) * 0.375);',
	'bottom-2': 'bottom: calc(var(--spacing) * 0.5);',
	'bottom-2.5': 'bottom: calc(var(--spacing) * 0.625);',
	'bottom-3': 'bottom: calc(var(--spacing) * 0.75);',
	'bottom-3.5': 'bottom: calc(var(--spacing) * 0.875);',
	'bottom-4': 'bottom: calc(var(--spacing) * 1);',
	'bottom-5': 'bottom: calc(var(--spacing) * 1.25);',
	'bottom-6': 'bottom: calc(var(--spacing) * 1.5);',
	'bottom-7': 'bottom: calc(var(--spacing) * 1.75);',
	'bottom-8': 'bottom: calc(var(--spacing) * 2);',
	'bottom-9': 'bottom: calc(var(--spacing) * 2.25);',
	'bottom-10': 'bottom: calc(var(--spacing) * 2.5);',
	'bottom-11': 'bottom: calc(var(--spacing) * 2.75);',
	'bottom-12': 'bottom: calc(var(--spacing) * 3);',
	'bottom-14': 'bottom: calc(var(--spacing) * 3.5);',
	'bottom-16': 'bottom: calc(var(--spacing) * 4);',
	'bottom-20': 'bottom: calc(var(--spacing) * 5);',
	'bottom-24': 'bottom: calc(var(--spacing) * 6);',
	'bottom-28': 'bottom: calc(var(--spacing) * 7);',
	'bottom-32': 'bottom: calc(var(--spacing) * 8);',
	'bottom-36': 'bottom: calc(var(--spacing) * 9);',
	'bottom-40': 'bottom: calc(var(--spacing) * 10);',
	'bottom-44': 'bottom: calc(var(--spacing) * 11);',
	'bottom-48': 'bottom: calc(var(--spacing) * 12);',
	'bottom-52': 'bottom: calc(var(--spacing) * 13);',
	'bottom-56': 'bottom: calc(var(--spacing) * 14);',
	'bottom-60': 'bottom: calc(var(--spacing) * 15);',
	'bottom-64': 'bottom: calc(var(--spacing) * 16);',
	'bottom-72': 'bottom: calc(var(--spacing) * 18);',
	'bottom-80': 'bottom: calc(var(--spacing) * 20);',
	'bottom-96': 'bottom: calc(var(--spacing) * 24);',
	'bottom-auto': 'bottom: auto;',

	// Left
	'left-0': 'left: 0;',
	'left-0.5': 'left: calc(var(--spacing) * 0.125);',
	'left-1': 'left: calc(var(--spacing) * 0.25);',
	'left-1.5': 'left: calc(var(--spacing) * 0.375);',
	'left-2': 'left: calc(var(--spacing) * 0.5);',
	'left-2.5': 'left: calc(var(--spacing) * 0.625);',
	'left-3': 'left: calc(var(--spacing) * 0.75);',
	'left-3.5': 'left: calc(var(--spacing) * 0.875);',
	'left-4': 'left: calc(var(--spacing) * 1);',
	'left-5': 'left: calc(var(--spacing) * 1.25);',
	'left-6': 'left: calc(var(--spacing) * 1.5);',
	'left-7': 'left: calc(var(--spacing) * 1.75);',
	'left-8': 'left: calc(var(--spacing) * 2);',
	'left-9': 'left: calc(var(--spacing) * 2.25);',
	'left-10': 'left: calc(var(--spacing) * 2.5);',
	'left-11': 'left: calc(var(--spacing) * 2.75);',
	'left-12': 'left: calc(var(--spacing) * 3);',
	'left-14': 'left: calc(var(--spacing) * 3.5);',
	'left-16': 'left: calc(var(--spacing) * 4);',
	'left-20': 'left: calc(var(--spacing) * 5);',
	'left-24': 'left: calc(var(--spacing) * 6);',
	'left-28': 'left: calc(var(--spacing) * 7);',
	'left-32': 'left: calc(var(--spacing) * 8);',
	'left-36': 'left: calc(var(--spacing) * 9);',
	'left-40': 'left: calc(var(--spacing) * 10);',
	'left-44': 'left: calc(var(--spacing) * 11);',
	'left-48': 'left: calc(var(--spacing) * 12);',
	'left-52': 'left: calc(var(--spacing) * 13);',
	'left-56': 'left: calc(var(--spacing) * 14);',
	'left-60': 'left: calc(var(--spacing) * 15);',
	'left-64': 'left: calc(var(--spacing) * 16);',
	'left-72': 'left: calc(var(--spacing) * 18);',
	'left-80': 'left: calc(var(--spacing) * 20);',
	'left-96': 'left: calc(var(--spacing) * 24);',
	'left-auto': 'left: auto;',

	// Inset
	'inset-0': 'inset: 0;',
	'inset-0.5': 'inset: calc(var(--spacing) * 0.125);',
	'inset-1': 'inset: calc(var(--spacing) * 0.25);',
	'inset-1.5': 'inset: calc(var(--spacing) * 0.375);',
	'inset-2': 'inset: calc(var(--spacing) * 0.5);',
	'inset-2.5': 'inset: calc(var(--spacing) * 0.625);',
	'inset-3': 'inset: calc(var(--spacing) * 0.75);',
	'inset-3.5': 'inset: calc(var(--spacing) * 0.875);',
	'inset-4': 'inset: calc(var(--spacing) * 1);',
	'inset-5': 'inset: calc(var(--spacing) * 1.25);',
	'inset-6': 'inset: calc(var(--spacing) * 1.5);',
	'inset-7': 'inset: calc(var(--spacing) * 1.75);',
	'inset-8': 'inset: calc(var(--spacing) * 2);',
	'inset-9': 'inset: calc(var(--spacing) * 2.25);',
	'inset-10': 'inset: calc(var(--spacing) * 2.5);',
	'inset-11': 'inset: calc(var(--spacing) * 2.75);',
	'inset-12': 'inset: calc(var(--spacing) * 3);',
	'inset-14': 'inset: calc(var(--spacing) * 3.5);',
	'inset-16': 'inset: calc(var(--spacing) * 4);',
	'inset-20': 'inset: calc(var(--spacing) * 5);',
	'inset-24': 'inset: calc(var(--spacing) * 6);',
	'inset-28': 'inset: calc(var(--spacing) * 7);',
	'inset-32': 'inset: calc(var(--spacing) * 8);',
	'inset-36': 'inset: calc(var(--spacing) * 9);',
	'inset-40': 'inset: calc(var(--spacing) * 10);',
	'inset-44': 'inset: calc(var(--spacing) * 11);',
	'inset-48': 'inset: calc(var(--spacing) * 12);',
	'inset-52': 'inset: calc(var(--spacing) * 13);',
	'inset-56': 'inset: calc(var(--spacing) * 14);',
	'inset-60': 'inset: calc(var(--spacing) * 15);',
	'inset-64': 'inset: calc(var(--spacing) * 16);',
	'inset-72': 'inset: calc(var(--spacing) * 18);',
	'inset-80': 'inset: calc(var(--spacing) * 20);',
	'inset-96': 'inset: calc(var(--spacing) * 24);',
	'inset-auto': 'inset: auto;',
	'inset-1/2': 'inset: calc(1/2 * 100%);',
	'inset-1/3': 'inset: calc(1/3 * 100%);',
	'inset-2/3': 'inset: calc(2/3 * 100%);',
	'inset-1/4': 'inset: calc(1/4 * 100%);',
	'inset-2/4': 'inset: calc(2/4 * 100%);',
	'inset-3/4': 'inset: calc(3/4 * 100%);',
	'inset-full': 'inset: 100%;',

	// Visibility
	visible: 'visibility: visible;',
	invisible: 'visibility: hidden;',
	collapse: 'visibility: collapse;',

	// Resize
	'resize-none': 'resize: none;',
	resize: 'resize: both;',
	'resize-y': 'resize: vertical;',
	'resize-x': 'resize: horizontal;',

	// Aspect Ratio
	'aspect-auto': 'aspect-ratio: auto;',
	'aspect-square': 'aspect-ratio: 1 / 1;',
	'aspect-video': 'aspect-ratio: var(--aspect-ratio-video); /* 16 / 9 */',

	// Columns
	'columns-1': 'columns: 1;',
	'columns-2': 'columns: 2;',
	'columns-3': 'columns: 3;',
	'columns-4': 'columns: 4;',
	'columns-5': 'columns: 5;',
	'columns-6': 'columns: 6;',
	'columns-7': 'columns: 7;',
	'columns-8': 'columns: 8;',
	'columns-9': 'columns: 9;',
	'columns-10': 'columns: 10;',
	'columns-11': 'columns: 11;',
	'columns-12': 'columns: 12;',
	'columns-auto': 'columns: auto;',
	'columns-3xs': 'columns: var(--container-3xs); /* 16rem (256px) */',
	'columns-2xs': 'columns: var(--container-2xs); /* 18rem (288px) */',
	'columns-xs': 'columns: var(--container-xs); /* 20rem (320px) */',
	'columns-sm': 'columns: var(--container-sm); /* 24rem (384px) */',
	'columns-md': 'columns: var(--container-md); /* 28rem (448px) */',
	'columns-lg': 'columns: var(--container-lg); /* 32rem (512px) */',
	'columns-xl': 'columns: var(--container-xl); /* 36rem (576px) */',
	'columns-2xl': 'columns: var(--container-2xl); /* 42rem (672px) */',
	'columns-3xl': 'columns: var(--container-3xl); /* 48rem (768px) */',
	'columns-4xl': 'columns: var(--container-4xl); /* 56rem (896px) */',
	'columns-5xl': 'columns: var(--container-5xl); /* 64rem (1024px) */',
	'columns-6xl': 'columns: var(--container-6xl); /* 72rem (1152px) */',
	'columns-7xl': 'columns: var(--container-7xl); /* 80rem (1280px) */',

	// Break After
	'break-after-auto': 'break-after: auto;',
	'break-after-avoid': 'break-after: avoid;',
	'break-after-all': 'break-after: all;',
	'break-after-avoid-page': 'break-after: avoid-page;',
	'break-after-page': 'break-after: page;',
	'break-after-left': 'break-after: left;',
	'break-after-right': 'break-after: right;',
	'break-after-column': 'break-after: column;',

	// Break Before
	'break-before-auto': 'break-before: auto;',
	'break-before-avoid': 'break-before: avoid;',
	'break-before-all': 'break-before: all;',
	'break-before-avoid-page': 'break-before: avoid-page;',
	'break-before-page': 'break-before: page;',
	'break-before-left': 'break-before: left;',
	'break-before-right': 'break-before: right;',
	'break-before-column': 'break-before: column;',

	// Break Inside
	'break-inside-auto': 'break-inside: auto;',
	'break-inside-avoid': 'break-inside: avoid;',
	'break-inside-avoid-page': 'break-inside: avoid-page;',
	'break-inside-avoid-column': 'break-inside: avoid-column;',

	// Box Decoration
	'box-decoration-clone': 'box-decoration-break: clone;',
	'box-decoration-slice': 'box-decoration-break: slice;',

	// Box Sizing
	'box-border': 'box-sizing: border-box;',
	'box-content': 'box-sizing: content-box;',

	// Float
	float: 'float: left;',
	'float-right': 'float: right;',
	'float-none': 'float: none;',

	// Clear
	clear: 'clear: left;',
	'clear-right': 'clear: right;',
	'clear-both': 'clear: both;',
	'clear-none': 'clear: none;',

	// Isolation
	isolation: 'isolation: isolate;',
	'isolation-auto': 'isolation: auto;',

	// Object Fit
	'object-contain': 'object-fit: contain;',
	'object-cover': 'object-fit: cover;',
	'object-fill': 'object-fit: fill;',
	'object-none': 'object-fit: none;',
	'object-scale-down': 'object-fit: scale-down;',

	// Object Position
	'object-bottom': 'object-position: bottom;',
	'object-center': 'object-position: center;',
	'object-left': 'object-position: left;',
	'object-left-bottom': 'object-position: left bottom;',
	'object-left-top': 'object-position: left top;',
	'object-right': 'object-position: right;',
	'object-right-bottom': 'object-position: right bottom;',
	'object-right-top': 'object-position: right top;',
	'object-top': 'object-position: top;',

	// Overflow
	'overflow-auto': 'overflow: auto;',
	'overflow-hidden': 'overflow: hidden;',
	'overflow-clip': 'overflow: clip;',
	'overflow-visible': 'overflow: visible;',
	'overflow-scroll': 'overflow: scroll;',
	'overflow-x-auto': 'overflow-x: auto;',
	'overflow-y-auto': 'overflow-y: auto;',
	'overflow-x-hidden': 'overflow-x: hidden;',
	'overflow-y-hidden': 'overflow-y: hidden;',
	'overflow-x-clip': 'overflow-x: clip;',
	'overflow-y-clip': 'overflow-y: clip;',
	'overflow-x-visible': 'overflow-x: visible;',
	'overflow-y-visible': 'overflow-y: visible;',
	'overflow-x-scroll': 'overflow-x: scroll;',
	'overflow-y-scroll': 'overflow-y: scroll;',

	// Overscroll
	'overscroll-auto': 'overscroll-behavior: auto;',
	'overscroll-contain': 'overscroll-behavior: contain;',
	'overscroll-none': 'overscroll-behavior: none;',
	'overscroll-y-auto': 'overscroll-behavior-y: auto;',
	'overscroll-y-contain': 'overscroll-behavior-y: contain;',
	'overscroll-y-none': 'overscroll-behavior-y: none;',
	'overscroll-x-auto': 'overscroll-behavior-x: auto;',
	'overscroll-x-contain': 'overscroll-behavior-x: contain;',
	'overscroll-x-none': 'overscroll-behavior-x: none;',
}
